force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This checkbox indicates if the ledger is active. Please contact Accounting Seed Support to edit this field.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LedgerManagerController.cls
/**
 * Created by christopherjohnson on 12/8/17.
 */

public with sharing class LedgerManagerController {

    @AuraEnabled
    public static List<Ledger__c> getLedgers() {
        List<Ledger__c> ledgerList = new List<Ledger__c>();

        try {
            for (Ledger__c ledger : LedgerHandler.getInstanceWithSharing(true).getPrimaryTransactionalLedgers()) {
                if (ledger.Active__c) {
                    ledgerList.add(ledger);
                }
            }
        }
        catch (Exception ex) {
           throw new AuraHandledException(ex.getMessage());
        }

        return ledgerList;
    }

    @AuraEnabled
    public static String getSelectedLedger() {
        Ledger_Custom_Settings__c lcs;
        try {
            lcs = Ledger_Custom_Settings__c.getInstance();
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        return lcs.Ledger_Id__c;
    }

    @AuraEnabled
    public static void setSelectedLedger(Id ledgerId) {
        try {
            Ledger_Custom_Settings__c lcs = Ledger_Custom_Settings__c.getInstance();
            lcs.Ledger_Id__c = ledgerId;
            SFDCSecurityUtils.upsertProxy(lcs);
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}