force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Accounting_Method__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Method__c</fullName>
    <inlineHelpText>This field defaults to “Accrual”. Select “Cash” if you want to use the cash method of accounting, “Accrual” if you want to track and report on an accrual basis, or “Accrual and Cash” if you want to track and report on both an accrual and cash basis.</inlineHelpText>
    <label>Accounting Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accrual</fullName>
                <default>true</default>
                <label>Accrual</label>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Accrual and Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This checkbox indicates if the ledger is active. Please contact Accounting Seed Support to edit this field.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Billing_Activity_Statement_Format__c.field-meta.xml
<CustomField>
    <fullName>Billing_Activity_Statement_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the billing activity statement format here. The billing activity statement format is the PDF format used to send billing activity statements to a customer.</inlineHelpText>
    <label>Billing Activity Statement Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Activity Statement</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Activity Statement</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Billing Activity Statement Format)</relationshipLabel>
    <relationshipName>Billing_Activity_Statement_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Billing_Outstanding_Statement_Format__c.field-meta.xml
<CustomField>
    <fullName>Billing_Outstanding_Statement_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the billing outstanding statement format here. The billing outstanding statement format is the PDF format used to send billing outstanding statements to a customer.</inlineHelpText>
    <label>Billing Outstanding Statement Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Outstanding Statement</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Outstanding Statement</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Billing Outstanding Statement Format)</relationshipLabel>
    <relationshipName>Billing_Outstanding_Statement_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Consolidation_Ledger_ID__c.field-meta.xml
<CustomField>
    <fullName>Consolidation_Ledger_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Consolidation Ledger ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account that the majority of payments are made from and that deposits are made to. When entering a cash receipt it will default to this bank account.</inlineHelpText>
    <label>Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only GL Accounts with Bank checked are allowed.</errorMessage>
        <filterItems>
            <field>GL_Account__c.Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Account__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Default_Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your primary billing format here. When you create a billing and leave this field blank, the default billing format will be selected after you press save.</inlineHelpText>
    <label>Default Billing Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Billing</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Default_Billing_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Packing_Slip_Format__c.field-meta.xml
<CustomField>
    <fullName>Default_Packing_Slip_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your primary packing slip format here. When you create a shipment record and leave this field blank, the default packing slip format will be selected after you press save.</inlineHelpText>
    <label>Default Packing Slip Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Packing Slip</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Packing Slip</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Default Packing Slip Format)</relationshipLabel>
    <relationshipName>Default_Packing_Slip_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Purchase_Order_Format__c.field-meta.xml
<CustomField>
    <fullName>Default_Purchase_Order_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your primary purchase order format here. When you create a purchase order and leave this field blank, the default purchase order format will be selected after you press save.</inlineHelpText>
    <label>Default Purchase Order Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Purchase Order</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Purchase Order</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Default Purchase Order Format)</relationshipLabel>
    <relationshipName>Default_Purchase_Order_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Financial_Reporter_Settings__c.field-meta.xml
<CustomField>
    <fullName>Financial_Reporter_Settings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Reporter Settings</label>
    <referenceTo>Financial_Reporter_Settings__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Is_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Is_Shadow__c</fullName>
    <formula>AND(NOT(ISBLANK(Related_Ledger__c)), ISPICKVAL(Accounting_Method__c , &apos;Cash&apos;),  ISPICKVAL(Related_Ledger__r.Accounting_Method__c, &apos;Accrual and Cash&apos;) )</formula>
    <label>Is Shadow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Related_Ledger__c.field-meta.xml
<CustomField>
    <fullName>Related_Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will be set automatically if the Accounting Method on the Ledger is “Accrual and Cash”.</inlineHelpText>
    <label>Related Ledger</label>
    <referenceTo>Ledger__c</referenceTo>
    <relationshipLabel>Related Ledgers</relationshipLabel>
    <relationshipName>Related_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Sales_Tax_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax_Company_Code__c</fullName>
    <inlineHelpText>Company Code in Avatax</inlineHelpText>
    <label>Sales Tax Company Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Tax_Settings__c.field-meta.xml
<CustomField>
    <fullName>Tax_Settings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The tax settings that will be associated with the ledger.</inlineHelpText>
    <label>Tax Settings</label>
    <referenceTo>Tax_Settings__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>You can only create one transactional ledger by default. Contact Accounting Seed Support for assistance in creating additional transactional ledgers.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Budget</fullName>
                <default>true</default>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Consolidations-Transactional</fullName>
            </value>
            <value>
                <fullName>Consolidations-Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LedgerHandler.cls
public with sharing class LedgerHandler {

    private static final String PACKAGE_QUALIFIER = GlobalVariables.PACKAGE_QUALIFIER;
    private static final Boolean IS_MULTI_CURRENCY_ENABLED = MultiCurrencyHandler.isMultiCurrencyEnabled;

    private static LedgerHandler instance;
    private static Map<String, Map<Id, Ledger__c>> availableLedgersBySharingContext;
    private SharingContext aSharingContext;
    private Boolean isFullFieldsSet;
    private String currentCompositeKey;

    public class LedgerException extends Exception {}

    private LedgerHandler(SharingContext sContext, Boolean queryAllFields) {
        this.aSharingContext = sContext;
        this.isFullFieldsSet = queryAllFields;
        this.currentCompositeKey = aSharingContext.name() + String.valueOf(isFullFieldsSet);
        init();
    }

    private static LedgerHandler getInstance(SharingContext sContext, Boolean queryAllFields) {
        if (instance == null || instance.aSharingContext != sContext || instance.isFullFieldsSet != queryAllFields) {
            instance = new LedgerHandler(sContext, queryAllFields);
        }
        return instance;
    }

    public static LedgerHandler getInstanceWithSharing(Boolean queryAllFields) {
        return getInstance(LedgerHandler.SharingContext.WITH_SHARING, queryAllFields);
    }

    public static LedgerHandler getInstanceWithSharing() {
        return getInstanceWithSharing(false);
    }

    public static LedgerHandler getInstanceWithoutSharing() {
        return getInstance(LedgerHandler.SharingContext.WITHOUT_SHARING, true);
    }

    private void init() {
        if (availableLedgersBySharingContext == null) {
            availableLedgersBySharingContext = new Map<String, Map<Id, Ledger__c>>();
        }
        try {
            if (availableLedgersBySharingContext.get(currentCompositeKey) == null) {
                switch on aSharingContext {
                    when WITH_SHARING {
                        availableLedgersBySharingContext.put(currentCompositeKey, new Map<Id, Ledger__c>(queryLedgers()));
                    }
                    when WITHOUT_SHARING {
                        availableLedgersBySharingContext.put(currentCompositeKey, new Map<Id, Ledger__c>(DomainUtils.getLedgers()));
                    }
                }
            }
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private List<Ledger__c> queryLedgers() {
        List<String> queryFields = new List<String>{'Id', 'Name', PACKAGE_QUALIFIER + 'Type__c', PACKAGE_QUALIFIER + 'Is_Shadow__c', PACKAGE_QUALIFIER + 'Active__c'};

        if (isFullFieldsSet) {
            queryFields.add(PACKAGE_QUALIFIER + 'Billing_Activity_Statement_Format__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Billing_Outstanding_Statement_Format__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Default_Bank_Account__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Default_Billing_Format__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Default_Purchase_Order_Format__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Default_Packing_Slip_Format__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Financial_Reporter_Settings__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Consolidation_Ledger_ID__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Tax_Settings__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Sales_Tax_Company_Code__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Tax_Settings__r.' + PACKAGE_QUALIFIER + 'Tax_Settings_Method__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Accounting_Method__c');
            queryFields.add(PACKAGE_QUALIFIER + 'Related_Ledger__c');
        }

        if (IS_MULTI_CURRENCY_ENABLED) {
            queryFields.add('CurrencyIsoCode');
        }

        String queryString = 'SELECT ' + String.join(queryFields,',') + ' FROM ' +
            PACKAGE_QUALIFIER + 'Ledger__c ORDER BY ' + PACKAGE_QUALIFIER + 'Type__c DESC, Name ASC';
        
        return (Ledger__c[]) Database.query(queryString);
    }

    public static void reset() {
        instance = null;
        availableLedgersBySharingContext = null;
    }

    public enum SharingContext {
        WITH_SHARING,
        WITHOUT_SHARING
    }


    //=================================================================================================
    //================================== INSTANCE UTILITY METHODS =====================================
    //=================================================================================================

    public List<Ledger__c> getAllLedgers() {
        return availableLedgersBySharingContext.get(currentCompositeKey).values();
    }

    public Map<Id, Ledger__c> getAllLedgersMap() {
        return availableLedgersBySharingContext.get(currentCompositeKey);
    }

    public List<Ledger__c> getPrimaryTransactionalLedgers() {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getTransactionalLedgers()) {
            if (!eachLedger.Is_Shadow__c) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public List<Ledger__c> getPrimaryActiveTransactionalLedgers() {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getTransactionalLedgers()) {
            if (!eachLedger.Is_Shadow__c && eachLedger.Active__c) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public List<Ledger__c> getTransactionalLedgers() {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getAllLedgers()) {
            if (eachLedger.Type__c == LedgerActions.LEDGER_TYPE_TRANSACTIONAL) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public List<Ledger__c> getAllTransactionalTypeLedgers() {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getAllLedgers()) {
            if (isTransactionalLedger(eachLedger.Type__c)) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public List<Ledger__c> getEliminationsTransactionalLedgers() {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getAllLedgers()) {
            if (eachLedger.Type__c == LedgerActions.LEDGER_TYPE_ELIMINATIONS_TRANSACTIONAL) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public List<Ledger__c> getTransactionalLedgersById(Set<Id> ledgerIds) {
        List<Ledger__c> result = new List<Ledger__c>();
        Map<Id, Ledger__c> transactionalLedgersMap = new Map<Id, Ledger__c>(
            getTransactionalLedgers()
        );
        for (Id lId : ledgerIds) {
            Ledger__c led = transactionalLedgersMap.get(lId);
            if (led != null) {
                result.add(led);
            }
        }
        return result;
    }

    public List<Ledger__c> getBudgetLedgers() {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getAllLedgers()) {
            if (eachLedger.Type__c == LedgerActions.LEDGER_TYPE_BUDGET) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public Ledger__c getLedgerById(Id ledgerId) {
        List<Ledger__c> result = getLedgerById(new Set<Id> {ledgerId});
        return (!result.isEmpty()) ? result[0] : null;
    }

    public List<Ledger__c> getLedgerById(Set<Id> ledgerIds) {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Id lId : ledgerIds) {
            Ledger__c led = getAllLedgersMap().get(lId);
            if (led != null) {
                result.add(led);
            }
        }
        return result;
    }

    public List<Ledger__c> getLedgerByName(Set<String> names) {
        List<Ledger__c> result = new List<Ledger__c>();
        for (Ledger__c eachLedger : getAllLedgers()) {
            if (names.contains(eachLedger.Name)) {
                result.add(eachLedger);
            }
        }
        return result;
    }

    public List<SelectOption> getTransactionalActiveLedgerSelectOptions() {
        return getTransactionalActiveLedgerSelectOptions(false);
    }

    public List<SelectOption> getTransactionalActiveLedgerSelectOptions(Boolean includeNone) {
        List<SelectOption> result  = new List<SelectOption>();
        //Include --None-- option
        if (includeNone) {
            result.add(new SelectOption('', '--' + Label.COMMON_NONE + '--'));
        }
        for (Ledger__c ledger : getPrimaryActiveTransactionalLedgers()) {
            result.add(new SelectOption(ledger.Id, ledger.Name));
        }
        if (result.isEmpty()) {
            result.add(new SelectOption('', '--' + Label.COMMON_NONE + '--'));
        }
        return result;
    }

    public List<SelectOption> getTransactionalLedgerSelectOptions() {
        return getTransactionalLedgerSelectOptions(false);
    }

    public List<SelectOption> getTransactionalLedgerSelectOptions(Boolean includeNone) {
        List<SelectOption> result  = new List<SelectOption>();
        //Include --None-- option
        if (includeNone) {
            result.add(new SelectOption('', '--' + Label.COMMON_NONE + '--'));
        }
        for (Ledger__c ledger : getPrimaryTransactionalLedgers()) {
            result.add(new SelectOption(ledger.Id, ledger.Name));
        }
        if (result.isEmpty()) {
            result.add(new SelectOption('', '--' + Label.COMMON_NONE + '--'));
        }
        return result;
    }

    public List<SelectOption> getBudgetLedgerSelectOptions() {
        List<SelectOption> result  = new List<SelectOption>();
        for (Ledger__c ledger : getBudgetLedgers()) {
            result.add(new SelectOption(ledger.Id, ledger.Name));
        }
        if (result.isEmpty()) {
            result.add(new SelectOption('', '--' + Label.COMMON_NONE + '--'));
        }
        return result;
    }

    public List<SelectOption> getBudgetLedgerSelectOptions(String currencyIsoCode) {
        if (IS_MULTI_CURRENCY_ENABLED && !String.isBlank(currencyIsoCode)) {
            List<SelectOption> result  = new List<SelectOption>();
            for (Ledger__c ledger : getBudgetLedgers()) {
                if (ledger.get('CurrencyIsoCode') == currencyIsoCode) {
                    result.add(new SelectOption(ledger.Id, ledger.Name));
                }
            }
            if (result.isEmpty()) {
                result.add(new SelectOption('', '--' + Label.COMMON_NONE + '--'));
            }
            return result;
        }
        else {
            return getBudgetLedgerSelectOptions();
        }
    }

    public Map<Id, Ledger__c> eliminationLedgersByConsolidationIds(Set<Id> consolidationLedgerIds) {
        List<Ledger__c> filteredLedgers = getEliminationLedgersByConsolidationIds(consolidationLedgerIds);
        Map<Id, Ledger__c> eliminationLedgersByConsolidationIds = new Map<Id, Ledger__c>();
        for (Ledger__c ledger : filteredLedgers) {
            eliminationLedgersByConsolidationIds.put(Id.valueOf(ledger.Consolidation_Ledger_ID__c), ledger);
        }
        return eliminationLedgersByConsolidationIds;
    }

    public List<Ledger__c> getEliminationLedgersByConsolidationIds(Set<Id> consolidationLedgerIds) {
        List<Ledger__c> filteredLedgers = new List<Ledger__c>();
        for (Ledger__c ledger : getAllLedgers()) {
            if (isEliminationLedger(ledger) && consolidationLedgerIds.contains(ledger.Consolidation_Ledger_ID__c)) {
                filteredLedgers.add(ledger);
            }
        }
        return filteredLedgers;
    }

    public Boolean isEliminationLedgerById(Id ledgerId) {
        return isEliminationLedger(getLedgerById(ledgerId));
    }

    public Boolean isActiveLedger(Id ledgerId) {
        return isActiveLedger(getLedgerById(ledgerId));
    }

    public Boolean isShadowLedger(Id ledgerId) {
        return isShadowLedger(getLedgerById(ledgerId));
    }

    public Boolean isCashLedger(Id ledgerId) {
        Ledger__c ledger = getLedgerById(ledgerId);
        return ledger.Accounting_Method__c != null && ledger.Accounting_Method__c == LedgerActions.ACCOUNTING_METHOD_CASH && String.isBlank(ledger.Related_Ledger__c);
    }

    public Boolean isAccrualAndCashLedger(Id ledgerId) {
        Ledger__c ledger = getLedgerById(ledgerId);
        return ledger.Accounting_Method__c != null && ledger.Accounting_Method__c == LedgerActions.ACCOUNTING_METHOD_ACCRUAL_CASH;
    }

    public Boolean isAccrualLedger(Id ledgerId) {
        Ledger__c ledger = getLedgerById(ledgerId);
        return ledger.Accounting_Method__c == null || ledger.Accounting_Method__c == LedgerActions.ACCOUNTING_METHOD_ACCRUAL;
    }

    public Ledger__c getShadowLedgerByParent(Id ledgerId) {
        Ledger__c ledger = getLedgerById(ledgerId);
        return ledger.Accounting_Method__c != null && ledger.Accounting_Method__c == LedgerActions.ACCOUNTING_METHOD_ACCRUAL_CASH
            ? getLedgerById(ledger.Related_Ledger__c) : ledger;
    }

    //=================================================================================================
    //================================== STATIC UTILITY METHODS =====================================
    //=================================================================================================

    public static Boolean isActiveLedger(Ledger__c ledger) {
        return ledger.Active__c;
    }

    public static Boolean isShadowLedger(Ledger__c ledger) {
        return ledger.Is_Shadow__c;
    }

    public static Id getLedgerId() {
        Ledger_Custom_Settings__c ledgerCustomSettings = Ledger_Custom_Settings__c.getValues(UserInfo.getUserId());
        return
            ledgerCustomSettings != null && LedgerHandler.getInstanceWithoutSharing().isActiveLedger(ledgerCustomSettings.Ledger_Id__c)
                ? ledgerCustomSettings.Ledger_Id__c
                : Ledger_Custom_Settings__c.getOrgDefaults().Ledger_Id__c;
    }

    public static Id getLedgerIdWithSharing() {
        Ledger_Custom_Settings__c ledgerCustomSettings = Ledger_Custom_Settings__c.getValues(UserInfo.getUserId());
        Id ledgerId =
                ledgerCustomSettings != null && LedgerHandler.getInstanceWithoutSharing().isActiveLedger(ledgerCustomSettings.Ledger_Id__c)
                    ? ledgerCustomSettings.Ledger_Id__c
                    : Ledger_Custom_Settings__c.getOrgDefaults().Ledger_Id__c;
        Ledger__c ledgerCheck = getInstanceWithSharing().getLedgerById(ledgerId);
        return ledgerCheck != null ? ledgerCheck.Id : null;
    }

    public static Id getOrgDefaultLedgerId() {
        return Ledger_Custom_Settings__c.getOrgDefaults().Ledger_Id__c;
    }

    public static Boolean isLedgerEqualLegacyLedger(Id ledgerId) {
        return (getLegacyDefaultLedgerId() == ledgerId);
    }

    public static Id getLegacyDefaultLedgerId() {
        Id result = AccountingSettingsHandler.getAccountingSettings().Legacy_Default_Ledger__c;
        if (result == null) {
            throw new LedgerException(
                Label.ERR_DEFAULT_LEDGER_NOT_SET_CORRECTLY_LEGACY_RECORDS
            );
        }
        return result;
    }

    public static String getLedgerCurrency(Id ledgerId) {
        String result = MultiCurrencyHandler.CORPORATE_CURRENCY;
        if (MultiCurrencyHandler.isMultiCurrencyEnabled) {
            Ledger__c ledger = LedgerHandler.getInstanceWithoutSharing().getLedgerById(ledgerId);
            result = ledger != null ? (String) ledger.get('CurrencyIsoCode') : result;
        }
        return result;
    }

    public static String getLedgerAccountingMethod(Id ledgerId) {
        Ledger__c ledger = LedgerHandler.getInstanceWithoutSharing().getLedgerById(ledgerId);
        return ledger?.Accounting_Method__c;
    }

    public static Ledger__c getShadowLedger(Id ledgerId) {
        Ledger__c ledger = LedgerHandler.getInstanceWithoutSharing().getLedgerById(ledgerId);
        return LedgerHandler.getInstanceWithoutSharing().getLedgerById(ledger?.Related_Ledger__c);
    }

    public static Boolean isLedgerCurrency(String sourceRecordCurrencyCode, Id ledgerId) {
        Boolean result = true;
        if (MultiCurrencyHandler.isMultiCurrencyEnabled) {
            String ledgerCurrency = getLedgerCurrency(ledgerId);
            result = ledgerCurrency.equalsIgnoreCase(sourceRecordCurrencyCode);
        }
        return result;
    }

    public static Boolean isUSDLedger(Id ledgerIdToCheck) {
        LedgerHandler lh = LedgerHandler.getInstanceWithoutSharing();
        Ledger__c ledgerToCheck;
        if (ledgerIdToCheck == null) {
            ledgerToCheck = lh.getAllLedgersMap().get(getLegacyDefaultLedgerId());
        }
        else {
            ledgerToCheck = lh.getAllLedgersMap().get(ledgerIdToCheck);
        }
        return (MultiCurrencyHandler.isMultiCurrencyEnabled)
            ? String.valueOf(ledgerToCheck.get('CurrencyIsoCode')) == 'USD'
            : true;
    }

    public static Boolean isConsolidationLedger(String ledgerType) {
        return
            ledgerType == LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_TRANSACTIONAL || ledgerType == LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_BUDGET;
    }

    public static Boolean isConsolidationLedger(Ledger__c aLedger) {
        return isConsolidationLedger(aLedger.Type__c);
    }

    public static Boolean isEliminationLedger(String ledgerType) {
        return
            ledgerType == LedgerActions.LEDGER_TYPE_ELIMINATIONS_TRANSACTIONAL || ledgerType == LedgerActions.LEDGER_TYPE_ELIMINATIONS_BUDGET;
    }

    public static Boolean isEliminationLedger(Ledger__c aLedger) {
        return isEliminationLedger(aLedger.Type__c);
    }

    public static Boolean isBudgetLedger(Ledger__c aLedger) {
        return
            aLedger.Type__c == LedgerActions.LEDGER_TYPE_BUDGET
                || aLedger.Type__c == LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_BUDGET
                || aLedger.Type__c == LedgerActions.LEDGER_TYPE_ELIMINATIONS_BUDGET;
    }

    public static Boolean isBudgetLedger(String ledgerType) {
        return
            ledgerType == LedgerActions.LEDGER_TYPE_BUDGET
                || ledgerType == LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_BUDGET
                || ledgerType == LedgerActions.LEDGER_TYPE_ELIMINATIONS_BUDGET;
    }

    public static Boolean isTransactionalLedger(String ledgerType) {
        return
            ledgerType == LedgerActions.LEDGER_TYPE_TRANSACTIONAL
                || ledgerType == LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_TRANSACTIONAL
                || ledgerType == LedgerActions.LEDGER_TYPE_ELIMINATIONS_TRANSACTIONAL;
    }

    public static Boolean isTransactionalLedger(Ledger__c aLedger) {
        return isTransactionalLedger(aLedger.Type__c);
    }

}