force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Accounting_Method__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Method__c</fullName>
    <inlineHelpText>This field defaults to “Accrual”. Select “Cash” if you want to use the cash method of accounting, “Accrual” if you want to track and report on an accrual basis, or “Accrual and Cash” if you want to track and report on both an accrual and cash basis.</inlineHelpText>
    <label>Accounting Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accrual</fullName>
                <default>true</default>
                <label>Accrual</label>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Accrual and Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Accounting_Method_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Method_Last_Modified_Date__c</fullName>
    <inlineHelpText>This date automatically populates when the Accounting Method is changed on the ledger. If the Accounting Method is “Accrual and Cash”, then this date will be on both the primary and shadow ledgers.</inlineHelpText>
    <label>Accounting Method Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This checkbox indicates if the ledger is active. Please contact Accounting Seed Support to edit this field.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Billing_Activity_Statement_Format__c.field-meta.xml
<CustomField>
    <fullName>Billing_Activity_Statement_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the billing activity statement format here. The billing activity statement format is the PDF format used to send billing activity statements to a customer.</inlineHelpText>
    <label>Billing Activity Statement Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Activity Statement</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Activity Statement</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Billing Activity Statement Format)</relationshipLabel>
    <relationshipName>Billing_Activity_Statement_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Billing_Outstanding_Statement_Format__c.field-meta.xml
<CustomField>
    <fullName>Billing_Outstanding_Statement_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the billing outstanding statement format here. The billing outstanding statement format is the PDF format used to send billing outstanding statements to a customer.</inlineHelpText>
    <label>Billing Outstanding Statement Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Outstanding Statement</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Outstanding Statement</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Billing Outstanding Statement Format)</relationshipLabel>
    <relationshipName>Billing_Outstanding_Statement_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Consolidation_Ledger_ID__c.field-meta.xml
<CustomField>
    <fullName>Consolidation_Ledger_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Consolidation Ledger ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account that the majority of payments are made from and that deposits are made to. When entering a cash receipt it will default to this bank account.</inlineHelpText>
    <label>Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only GL Accounts with Bank checked are allowed.</errorMessage>
        <filterItems>
            <field>GL_Account__c.Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Account__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Default_Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your primary billing format here. When you create a billing and leave this field blank, the default billing format will be selected after you press save.</inlineHelpText>
    <label>Default Billing Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Billing</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Default_Billing_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Packing_Slip_Format__c.field-meta.xml
<CustomField>
    <fullName>Default_Packing_Slip_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your primary packing slip format here. When you create a shipment record and leave this field blank, the default packing slip format will be selected after you press save.</inlineHelpText>
    <label>Default Packing Slip Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Packing Slip</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Packing Slip</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Default Packing Slip Format)</relationshipLabel>
    <relationshipName>Default_Packing_Slip_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Default_Purchase_Order_Format__c.field-meta.xml
<CustomField>
    <fullName>Default_Purchase_Order_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select your primary purchase order format here. When you create a purchase order and leave this field blank, the default purchase order format will be selected after you press save.</inlineHelpText>
    <label>Default Purchase Order Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Billing_Format__c.Type__c</field>
            <operation>equals</operation>
            <value>Purchase Order</value>
        </filterItems>
        <infoMessage>The type on the PDF Format must be Purchase Order</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Billing_Format__c</referenceTo>
    <relationshipLabel>Ledgers (Default Purchase Order Format)</relationshipLabel>
    <relationshipName>Default_Purchase_Order_Formats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Enable_Pre_Tax_Discount_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Pre_Tax_Discount_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When enabled, discounts on billings will be calculated on a pre-tax basis (Sub-Total).  When unchecked, discounts will be calculated on the Total.</inlineHelpText>
    <label>Enable Pre-Tax Discount Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Financial_Reporter_Settings__c.field-meta.xml
<CustomField>
    <fullName>Financial_Reporter_Settings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Reporter Settings</label>
    <referenceTo>Financial_Reporter_Settings__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Related_Ledger__c.field-meta.xml
<CustomField>
    <fullName>Related_Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will be set automatically if the Accounting Method on the Ledger is “Accrual and Cash”.</inlineHelpText>
    <label>Related Ledger</label>
    <referenceTo>Ledger__c</referenceTo>
    <relationshipLabel>Related Ledgers</relationshipLabel>
    <relationshipName>Related_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>You can only create one transactional ledger by default. Contact Accounting Seed Support for assistance in creating additional transactional ledgers.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Budget</fullName>
                <default>true</default>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Consolidations-Transactional</fullName>
            </value>
            <value>
                <fullName>Consolidations-Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LedgerFieldUpdateValidator.cls
public with sharing class LedgerFieldUpdateValidator extends SourceDocumentUpdateFieldValidator {
    public static Set<SObjectField> lockedUpdateFieldsNormalLedger = new Set<SObjectField>{
            Ledger__c.Accounting_Method__c,
            Ledger__c.Related_Ledger__c,
            Ledger__c.Active__c,
            Ledger__c.Accounting_Method_Last_Modified_Date__c
    };
    public static Set<SObjectField> lockedUpdateFieldsL {
        get {
            lockedUpdateFieldsL = new Set<SObjectField> {
                    Ledger__c.Accounting_Method__c,
                    Ledger__c.Billing_Activity_Statement_Format__c,
                    Ledger__c.Billing_Outstanding_Statement_Format__c,
                    Ledger__c.Consolidation_Ledger_ID__c,
                    Ledger__c.Default_Bank_Account__c,
                    Ledger__c.Default_Billing_Format__c,
                    Ledger__c.Default_Packing_Slip_Format__c,
                    Ledger__c.Default_Purchase_Order_Format__c,
                    Ledger__c.Enable_Pre_Tax_Discount_Calculation__c,
                    Ledger__c.Financial_Reporter_Settings__c,
                    Ledger__c.Related_Ledger__c,
                    Ledger__c.Type__c,
                    Ledger__c.Active__c,
                    Ledger__c.Accounting_Method_Last_Modified_Date__c
            };

            if (MultiCurrencyHandler.isMultiCurrencyEnabled) {
                lockedUpdateFieldsL.add(Schema.SObjectType.Ledger__c.fields.getMap().get('CurrencyIsoCode'));
            }
            return lockedUpdateFieldsL;
        }
        private set;
    }

    public LedgerFieldUpdateValidator() {
        lockedUpdateFields = lockedUpdateFieldsL;
        customValidationErrorMsg = Label.ERR_ACCOUNTING_METHOD_CHANGE_FROM_CASH_TO_ACCRUAL;
    }

    public override void setValidationRules() {
        preventUpdateAction();
        preventUpdateCustomAction();
    }

    public override Boolean skipLegacyRecordValidation(SObjectField field) {
        Boolean isShadowLedgerAndNotEL = String.isNotBlank((String)oldObj.get(Ledger__c.Related_Ledger__c))
                && LedgerHandler.isShadowLedger((Ledger__c)oldObj)
                && !LedgerHandler.isEliminationLedger((String)oldObj.get(Ledger__c.Type__c));
        Boolean isSkip = !(lockedUpdateFieldsNormalLedger.contains(field) || isShadowLedgerAndNotEL);

        if (!isSkip && lockedUpdateFieldsWrapper != null) {
            if (isShadowLedgerAndNotEL) {
                lockedUpdateFieldsWrapper.fields = lockedUpdateFieldsL;
            } else {
                lockedUpdateFieldsWrapper.fields = lockedUpdateFieldsNormalLedger;
            }
        }

        if (field == Ledger__c.Accounting_Method__c && !CONSOLIDATIONS_ELIMINATIONS_TYPES.contains((String)newObj.get(Ledger__c.Type__c))) {
            // allow Accounting Method field population for legacy items.
            if (!isSkip && field == Ledger__c.Accounting_Method__c && isFirstFieldChanges(field)) {
                isSkip = true;
            }

            if (!isSkip && (changedFromAccrualToAccrualCash() || changedFromAccrualToCash())) {
                isSkip = true;
            }
        }

        if (field == Ledger__c.Accounting_Method__c
                && CONSOLIDATIONS_ELIMINATIONS_TYPES.contains((String)newObj.get(Ledger__c.Type__c))
                && newObj.get(Ledger__c.Accounting_Method__c) != oldObj.get(Ledger__c.Accounting_Method__c)) {
            isSkip = true;
        }

        return isSkip;
    }

    private Boolean changedFromAccrualToAccrualCash() {
        return LedgerActions.isAccrualAccountingMethod(oldObj) && LedgerActions.isAccrualAndCashAccountingMethod(newObj);
    }

    private Boolean changedFromAccrualToCash() {
        return LedgerActions.isCashAccountingMethod(newObj) && LedgerActions.isAccrualAccountingMethod(oldObj);
    }



    public override Boolean customValidationRules() {
        return oldObj.get(Ledger__c.Accounting_Method__c) == LedgerActions.ACCOUNTING_METHOD_CASH
            && newObj.get(Ledger__c.Accounting_Method__c) == LedgerActions.ACCOUNTING_METHOD_ACCRUAL ;
    }

    public static final Set<String> CONSOLIDATIONS_TYPES = new Set<String>{
            LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_TRANSACTIONAL,
            LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_BUDGET
    };

    public static final Set<String> ELIMINATIONS_TYPES = new Set<String>{
            LedgerActions.LEDGER_TYPE_ELIMINATIONS_TRANSACTIONAL,
            LedgerActions.LEDGER_TYPE_ELIMINATIONS_BUDGET
    };

    public static final Set<String> CONSOLIDATIONS_ELIMINATIONS_TYPES = new Set<String>{
            LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_TRANSACTIONAL,
            LedgerActions.LEDGER_TYPE_CONSOLIDATIONS_BUDGET,
            LedgerActions.LEDGER_TYPE_ELIMINATIONS_TRANSACTIONAL,
            LedgerActions.LEDGER_TYPE_ELIMINATIONS_BUDGET
    };
}